apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: marcioduarte89/gateway:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    app: gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: gateway
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-pod
spec:
  replicas: 1
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-ctr
        image: marcioduarte89/dotnetcorecicd:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-pod
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: hello-world
  