version: '3.3'
services:
    testservice:
        image: marcioduarte89/testservice
        build:
          context: ./TestService
          dockerfile: Dockerfile
        ports:
            - "9001:80"