services:
    test.service:
        image: dotnetcorecicd/testservice:${TAG:-latest}
        build:
          context: ./TestService
          dockerfile: Dockerfile
        ports:
            - "9001:80"